core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parse.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parse/urls.py
from django.urls import path
from . import views


app_name = 'parse'


urlpatterns = [
    path('', views.index, name='index'),
    path('excel', views.form_upload, name='parse'),
    path('convert', views.excel_parse_to_json, name='convert')
]

parse/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.validators import FileExtensionValidator, validate_email

# Create your models here.


class ExcelUpload(models.Model):
    document = models.FileField(upload_to='upload/', validators=[FileExtensionValidator(['xlsx'])])
    upload_at = models.DateTimeField(auto_now_add=True)


# class Email(models.Model):
#     upload = models.EmailField(max_length=50, blank=False, unique=True, validators=[validate_email])
#     upload_time = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.upload

parse/forms.py
from django import forms
from .models import ExcelUpload


class ExcelUploadForm(forms.ModelForm):
    class Meta:
        model = ExcelUpload
        fields = ('document', )


# class EmailForm(forms.ModelForm):
#     class Meta:
#         model = Email
#         fields = ('upload',)

parse/views.py
import os
import pandas as pd
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from core.settings import BASE_DIR
from .forms import ExcelUploadForm
from .models import ExcelUpload


# Create your views here.


def index(request):
    pass
    return render(request, 'index.html')


def home(request):
    excel_upload = ExcelUpload.objects.all()
    return render(request, 'excel.html', {'excel_upload': excel_upload})


def form_upload(request):
    if request.method == 'POST':
        form = ExcelUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('parse:convert')
    else:
        form = ExcelUploadForm()
    return render(request, 'excel.html', {'form': form})


def excel_parse_to_json(request):
    directory = os.path.join(BASE_DIR, r'media\upload')
    for file in os.listdir(directory):
        filename = os.fsdecode(file)
        if filename.endswith('.xlsx'):
            file_name = os.path.join(directory, filename)
            df = pd.read_excel(file_name, encoding='utf-8')
            data = df.dropna(axis=0, how='any')
            data.columns = data.columns.map(lambda x: str(x))
            data.columns = data.columns.map(lambda x: x.replace('\n', ''))
            final_data = data.to_dict(orient='records')
            return render(request, 'result.html', {'final_data': final_data})
        else:
            return render(request, 'result.html', messages.error(request, 'Error! No excel file found.'))



# file = request.FILES.get('file')
# filename = file.name
# ExcelUpload.objects.create(document=file)
# file_path = request.data.get('file_path')
# print(file_path, request.data)
# file = request.FILES.get('file')
# filename = file.name
# pdf_file_name = filename[-4:]
# ExcelUpload.objects.create(document=file)

parse/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Simple File Upload</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

parse/templates/excel.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
  <form action="#" method="get">
    <input type="text" value="8" name="mytextbox" size="1"/>
    <input type="submit" class="btn" value="Click" name="mybtn">
  </form>

  <p><a href="{% url 'parse:index' %}">Return to home</a></p>
{% endblock %}

parse/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <ul>
    <li>
      <a href="{% url 'parse:parse' %}">Model Form Upload</a>
    </li>
  </ul>

  <p>Uploaded files:</p>
  <ul>
    {% for obj in documents %}
      <li>
        <a href="{{ obj.document.url }}">{{ obj.document.name }}</a>
        <small>(Uploaded at: {{ obj.uploaded_at }})</small>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

parse/templates/index.html
{% load static %}
<!DOCTYPE html>

<html lang='en'>

    <head>

        <meta charset='UTF-8' />

        <meta name='viewport' content='width-device-width, initial-scale=1.0' />

        <title> Excel API </title>

        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css' />

        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">

    </head>
    <body>
        <div class='jumbotron jumbotron-fluid'>
            <div class='container-fluid' id='flex'>
                <div class='row' id='margin'>
                    <div class='col-lg-4 col-md-4' id='img'>
                        <img src='https://res.cloudinary.com/payne/image/upload/v1594338793/layers.png' alt='#' /> microAPI
                    </div>
                    <div class='col-lg-4 col-md-4'>
                        <nav class='nav nav-pills'>
                            <a class='nav-link active' href='#'>Home</a>
                            <a class='nav-link' href='#'>About Us </a>
                            <a class='nav-link' href='#'>Contact Us</a>
                            <a class='nav-link' href='#'>Documentation</a>
                        </nav>

                        <div class="navbar col-lg-4 col-md-4">
                        <div class="dropdown">
                            <button class="dropbtn">Home 
                            <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="dropdown-content">
                            <a href="#">About Us</a>
                            <a href="#">Contact Us</a>
                            <a href="#">Documentation</a>
                            </div>
                        </div> 
                        </div>
                    </div>
<!--                    <div class='col-lg-4 col-md-4' id='h-btns'>-->
<!--                        <a href="#" class="btn btn-primary" id='sign-in-btn'>Sign in</a>-->
<!--                        <a href="#" class="btn btn-primary" id='sign-up-btn'>Sign up</a>-->
<!--                    </div>-->
                </div>
            </div>
        </div>

        <div class='container text_container'>
            <div class='row' id='flexed'>
                <div class='col-lg-6 col-md-6 col-sm-6 main_text' id='main_text'>
                    <h2> Welcome to the </h2> <h2>Excel API resource </h2>
                        <div class='row btn_div' id='btn_div'>
                            <a href="{% url 'parse:parse' %}" class="btn btn-primary ">FILE UPLOAD</a>
                            <a href="#" class="btn btn-primary ">CDN UPLOAD</a>
                        </div>
                </div>
                <div class='col-lg-6 col-md-6 col-sm-12'>
                    <img src='https://res.cloudinary.com/payne/image/upload/v1594341795/header_illustratn_1.png'
                         class='main_img' alt='...' />
                </div>
            </div>
        </div>

        <footer>	&copy; 2020 microAPI </footer>
    </body>
</html>